{% set name = "multiaddr" %}
{% set version = "0.0.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 30b2695189edc3d5b90f1c303abb8f02d963a3a4edf2e7178b975eb417ab0ecf

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - base58
    - netaddr
    - python >={{ python_min }}
    - six
    - varint
    - idna

test:
  imports:
    - multiaddr
    - multiaddr.codecs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/multiformats/py-multiaddr
  summary: Python implementation of jbenet's multiaddr
  doc_url: https://pythonhosted.org/multiaddr/
  license: MIT
  license_file: LICENSE-MIT

extra:
  recipe-maintainers:
    - step21
